import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,step,serialize} from '../src/engine.mjs';
import {K6_RESOURCE_REGEN} from '../src/worldsim-resource-policy.mjs?v=0.5.0';
import {RESOURCE_REGEN_AUTHORITY,applyWorldResourceRegeneration} from '../src/worldsim-resource-authority.mjs';

function legacyOracle(s){
  if(s.tick%120===0)for(const n of s.nodes)if(n.type==='food')n.amount=Math.min(n.max,n.amount+3);
  if(s.tick%720===0)for(const n of s.nodes)if(n.type==='wood')n.amount=Math.min(n.max,n.amount+1);
}
function fixture(tick){
  const s=createWorld(230926);s.tick=tick;
  for(const n of s.nodes)n.amount=Math.max(0,Math.min(n.max,(n.id*7+tick)%Math.max(1,n.max)));
  return s;
}

test('WM4.1 policy is exact K6 parity from one shared contract',()=>{
  assert.equal(RESOURCE_REGEN_AUTHORITY.food,K6_RESOURCE_REGEN.food);
  assert.equal(RESOURCE_REGEN_AUTHORITY.wood,K6_RESOURCE_REGEN.wood);
  assert.equal(RESOURCE_REGEN_AUTHORITY.stone,K6_RESOURCE_REGEN.stone);
  assert.equal(RESOURCE_REGEN_AUTHORITY.food.periodTicks,120);
  assert.equal(RESOURCE_REGEN_AUTHORITY.food.amount,3);
  assert.equal(RESOURCE_REGEN_AUTHORITY.wood.periodTicks,720);
  assert.equal(RESOURCE_REGEN_AUTHORITY.wood.amount,1);
  assert.equal(RESOURCE_REGEN_AUTHORITY.stone.periodTicks,null);
  assert.equal(RESOURCE_REGEN_AUTHORITY.stone.amount,0);
  assert.equal(RESOURCE_REGEN_AUTHORITY.behavior,'k6-parity');
});

test('WorldSim regeneration matches legacy oracle across boundaries',()=>{
  for(const tick of [1,119,120,239,240,719,720,721,1439,1440]){
    const a=fixture(tick),b=structuredClone(a);
    applyWorldResourceRegeneration(a);legacyOracle(b);
    assert.deepEqual(a.nodes,b.nodes,'tick '+tick);
  }
});

test('stone is never regenerated by WM4.1',()=>{
  const s=fixture(720),before=s.nodes.filter(n=>n.type==='stone').map(n=>n.amount);
  applyWorldResourceRegeneration(s);
  assert.deepEqual(s.nodes.filter(n=>n.type==='stone').map(n=>n.amount),before);
});

test('engine boundary at tick 120 still adds food +3 and no wood',()=>{
  const s=createWorld(42);s.tick=119;s.stock.food=s.stock.wood=s.stock.stone=999;
  for(const n of s.nodes)n.amount=0;
  step(s,1);
  assert.ok(s.nodes.filter(n=>n.type==='food').every(n=>n.amount===3));
  assert.ok(s.nodes.filter(n=>n.type==='wood').every(n=>n.amount===0));
  assert.ok(s.nodes.filter(n=>n.type==='stone').every(n=>n.amount===0));
});

test('engine boundary at tick 720 adds food +3 and wood +1 exactly',()=>{
  const s=createWorld(77);s.tick=719;s.stock.food=s.stock.wood=s.stock.stone=999;
  for(const n of s.nodes)n.amount=0;
  step(s,1);
  assert.ok(s.nodes.filter(n=>n.type==='food').every(n=>n.amount===3));
  assert.ok(s.nodes.filter(n=>n.type==='wood').every(n=>n.amount===1));
  assert.ok(s.nodes.filter(n=>n.type==='stone').every(n=>n.amount===0));
});

test('WM4.1 adds no save fields',()=>{
  const s=createWorld(9),before=JSON.parse(serialize(s));
  s.tick=120;applyWorldResourceRegeneration(s);
  const after=JSON.parse(serialize(s));
  assert.deepEqual(Object.keys(after).sort(),Object.keys(before).sort());
  assert.equal(after.version,before.version);
});


test('WM4.1 regeneration is a no-op at initial tick zero',()=>{
  const s=createWorld(31415);for(const n of s.nodes)n.amount=0;
  const added=applyWorldResourceRegeneration(s);
  assert.equal(added,0);
  assert.ok(s.nodes.every(n=>n.amount===0));
});
